"use client"
import CardMotion from "../motion/CardMotion"
import TextMotion from "../motion/TextMotion"
import ZoomElement from "../motion/ZoomElement"
import CodeBlockLight from "./CodeBlockLight"

const Exemple = () => {
    return (
        <section id="exemples" className="max-w-xl mx-auto  space-y-10 mt-20">

            <TextMotion delay={0.5}>
                <p className="text-center text-2xl  lg:text-3xl italic">📦 API Examples</p>

            </TextMotion>


            <ZoomElement>
                <CodeBlockLight
                    filename="scan-project.ts"
                    code={`import { scanProject } from "next-mahine-rsc-inspector";

async function run() {
  const result = await scanProject(process.cwd());

  console.log("Total files:", result?.total);
  console.log("Client components:", result?.client);
  console.log("Server components:", result?.server);
  console.log("Client percentages:", result?.ratioClient);
  console.log("Server percentages:", result?.ratioServer);

}

run();`}
                />
            </ZoomElement>



            <ZoomElement>
                <CodeBlockLight
                    filename="analyze-file.ts"
                    code={`import { analyzeFile } from "next-mahine-rsc-inspector";

async function run() {

 //You put the path of the file here
  const filePath = "src/app/page.tsx";

  const result = await analyzeFile(filePath);


  console.log("File path:", filePath);
  console.log("Is client:", result?.isClient);
}

run();`}
                />
            </ZoomElement>



            



            <CardMotion delay={0.5}>

                <div className="mb-3 max-w-2xl lg:text-md rounded-md border border-zinc-200 bg-zinc-50 px-4 py-2 text-xs text-zinc-700 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
                    <strong className="text-zinc-900 dark:text-zinc-100">
                        Combined workflow
                    </strong>{" "}
                    shows how to scan a project, compute stats, and analyze files together.
                </div>

            </CardMotion>



            <CardMotion delay={0.6}>

                <div className="mb-3 max-w-2xl lg:text-md rounded-md border border-zinc-200 bg-zinc-50 px-4 py-2 text-xs text-zinc-700 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
                    <strong className="text-zinc-900 dark:text-zinc-100">
                        Combined workflow
                    </strong>{" "}
                    shows how to scan a project, compute stats, and analyze files together.
                </div>

            </CardMotion>





            <CardMotion delay={0.7}>
                <div className="mb-3 max-w-2xl lg:text-md rounded-md border border-zinc-200 bg-zinc-50 px-4 py-2 text-xs text-zinc-700 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
                    <strong className="text-zinc-900 dark:text-zinc-100">
                        JSON output
                    </strong>{" "}
                    example of the structured report generated by the library.
                </div>
            </CardMotion>


            <ZoomElement>
                <CodeBlockLight
                    filename="report.json"
                    code={`{
  "totalFiles": 190,
  "clientComponents": 88,
  "serverComponents": 102,
  "clientRatio": 46,
  "serverRatio": 54
}`}
                />
            </ZoomElement>



        </section>
    )
}

export default Exemple
