"use client"
import CardMotion from "../motion/CardMotion"
import TextMotion from "../motion/TextMotion"
import ZoomElement from "../motion/ZoomElement"
import CodeBlockLight from "./CodeBlockLight"

const Exemple = () => {
    return (
        <section id="exemples" className="max-w-xl mx-auto  space-y-10 mt-20">

            <TextMotion delay={0.5}>
                <p className="text-center text-2xl  lg:text-3xl italic">📦 API Examples</p>

            </TextMotion>


            <ZoomElement>
                <CodeBlockLight
                    filename="scan-project.ts"
                    code={`import { scanProject } from "next-mahine-rsc-inspector";

async function run() {
  const result = await scanProject(process.cwd());

  console.log("Total files:", result?.total);
  console.log("Client components:", result?.client);
  console.log("Server components:", result?.server);
  console.log("Client percentages:", result?.ratioClient %);
  console.log("Server percentages:", result?.ratioServer %);

}

run();`}
                />
            </ZoomElement>



            <ZoomElement>
                <CodeBlockLight
                    filename="analyze-file.ts"
                    code={`import { analyzeFile } from "next-mahine-rsc-inspector";

async function run() {

 //You put the path of the file here
  const filePath = "src/app/page.tsx";

  const result = await analyzeFile(filePath);


  console.log("File path:", filePath);
  console.log("Is client:", result?.isClient);
}

run();`}
                />
            </ZoomElement>



            



            <CardMotion delay={0.5}>

                <div className="mb-3 max-w-2xl lg:text-md rounded-md border border-zinc-200 bg-zinc-50 px-4 py-2 text-xs text-zinc-700 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
                    <strong className="text-zinc-900 dark:text-zinc-100">
                        Combined workflow
                    </strong>{" "}
                    shows how to scan a project, compute stats, and analyze files together.
                </div>

            </CardMotion>



            <CardMotion delay={0.6}>

                <div className="mb-3 max-w-2xl lg:text-md rounded-md border border-zinc-200 bg-zinc-50 px-4 py-2 text-xs text-zinc-700 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
                    <strong className="text-zinc-900 dark:text-zinc-100">
                        Combined workflow
                    </strong>{" "}
                    shows how to scan a project, compute stats, and analyze files together.
                </div>

            </CardMotion>





            <CardMotion delay={0.7}>
                <div className="mb-3 max-w-2xl lg:text-md rounded-md border border-zinc-200 bg-zinc-50 px-4 py-2 text-xs text-zinc-700 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
                    <strong className="text-zinc-900 dark:text-zinc-100">
                        JSON output
                    </strong>{" "}
                    example of the structured report generated by the library.
                </div>
            </CardMotion>


            <ZoomElement>
                <CodeBlockLight
                    filename="report.json"
                    code={`
✅ App directory: src
{
  "projectName": "next-mahine-rsc-doc",
  "projectRoot": "/media/mahine/2cd32d5c-0a41-43a3-9e8e-d67f38891ca2/next-mahine-rsc-doc",
  "appDir": "/media/mahine/2cd32d5c-0a41-43a3-9e8e-d67f38891ca2/next-mahine-rsc-doc/src",
  "folders": {
    "app": {
      "server": 3,
      "client": 0
    },
    "lib": {
      "server": 1,
      "client": 0
    },
    "components/goTop": {
      "server": 0,
      "client": 2
    },
    "components/ui": {
      "server": 1,
      "client": 1
    },
    "components/web": {
      "server": 1,
      "client": 0
    },
    "components/ui/dark": {
      "server": 0,
      "client": 2
    },
    "components/web/api": {
      "server": 0,
      "client": 1
    },
    "components/web/author": {
      "server": 0,
      "client": 1
    },
    "components/web/cli": {
      "server": 1,
      "client": 1
    },
    "components/web/exemples": {
      "server": 0,
      "client": 2
    },
    "components/web/footer": {
      "server": 0,
      "client": 1
    },
    "components/web/hero": {
      "server": 0,
      "client": 1
    },
    "components/web/install": {
      "server": 1,
      "client": 2
    },
    "components/web/license": {
      "server": 0,
      "client": 1
    },
    "components/web/logoSection": {
      "server": 0,
      "client": 1
    },
    "components/web/motion": {
      "server": 0,
      "client": 3
    },
    "components/web/nav": {
      "server": 0,
      "client": 3
    }
  },
  "total": 30,
  "client": 22,
  "server": 8,
  "ratioServer": 27,
  "ratioClient": 73
}`}
                />
            </ZoomElement>



        </section>
    )
}

export default Exemple
